version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "127.0.0.1:5678:5678" # Localhost only for security
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=Europe/Berlin
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - mcp-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  mcp-net:
    external: true

volumes:
  n8n_data:
